adding a fully containerized build to the dockerfile
ejether/knamespacer pull request #5
Opened 2024-02-03 22:34 UTC by pthomison

- Copy/Pasta'd my Dockefile golang builder
- Defaulting make build to run tidy as well. I find this useful just to make sure everything is gtg with the mod file
-

2024-02-03 23:05 UTC, pthomison commented
Also dropped the `goldilocks` labels on the dockerfile, not sure if those were a copy/pasta. Can add them back if we want

2024-02-09 21:15 UTC, ejether commented
Word! The `golidlocks` tags were total copy-pasta.

2024-02-09 21:21 UTC, ejether requested changes
The multi part build was on my radar, thanks for taking that. 
You didn't add any whitespace errors, but since they show up in this PR, I though, might as well fix them here.

Is the uncomment of the test in the `Makefile` used here for anything. 
I see there are more changes in the next PR.

2024-02-09 21:21 UTC, ejether commented on testing.Dockerfile
> +RUN go mod download
```suggestion
RUN go mod download

```

2024-02-09 21:21 UTC, ejether commented on Makefile
>  # 	venom run e2e/tests/* --output-dir e2e/results --log info --strictf
```suggestion
# 	venom run e2e/tests/* --output-dir e2e/results --log info --strictf

```

2024-02-09 21:21 UTC, ejether commented on Dockerfile
> +ENTRYPOINT ["/knamespacer"]
```suggestion
ENTRYPOINT ["/knamespacer"]

```

2024-02-09 21:21 UTC, ejether commented on .gitignore
> +coverage.txt
```suggestion
coverage.txt

```

2024-02-09 21:58 UTC, ejether approved these changes

2024-02-09 21:58 UTC, merged